#!/usr/bin/python
# Author <Jaideep Khandelwal jdk2588@gmail.com>

import facebook

ACCESS_TOKEN='''CAACEdEose0cBAAetWamjgq89YBxZAXFSnVeZB1AfuevM3zZC3hfvlROxonhkoGSV50M1OvZBeYxraGxT2W2xnEP4lK0RKpXwnfVmZAZCclgZAfTcBJXntdXRYr4Kx11tdIQ7JEijdsQVtom3mZAnGz4REuHq0XbVQjQua4R4LJrfZAXOrFVF0sv2pEBUIc8KSMZALXMbNecVzV1EOLrgNCQIohjEWMHCnVR4IZD'''
facebook_conn = facebook.GraphAPI(ACCESS_TOKEN)
